apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: m3nppda1i-java-quarkus
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-fb4f61297b.tcz4.p3.openshiftapps.com/rhtap/rhtap-qe-java-quarkus:c0b7782be7c90750575ff4d52e72dfb11602cc67@sha256:d9e4042758203b76b4133bc57933f1c7e3c356f9eee70c22b257090b6e887f17
        name: container-image  
